
# Learning diary

*Write a short description about the course and add a link to your github repository here. This is an R markdown (.Rmd) file so you can use R markdown syntax. See the 'Useful links' page in the mooc area (chapter 1) for instructions.*

## Chapter 1.

This is the first assigment on the University of Helsinki MOOC.

My git repository is in following address:
https://github.com/toparvia/IODS-project.git

This is the first entry in the in the learning diary. The first lecture introduced basic methods of collaboration such as using Git for your code and writing reports using Markdown and Knitr. I have used these before, but I'm more familiar using them in UNIX than with Windows computers. I felt quite clumsy these, as in my own PhD project I don't need to collaborate on the methods part as much. I chose to use Git hub desktop and RStudio as it was recommended in the course materials.

I also went through the R Short and Sweet. I think only trouble was with last assignment. I think my approach of function was in different order and it didn't accept it at first. Finally I achieved to a solution that satisfied the test. I'm curious to see how the course will develop in the future.

Under here is just some tests of RMarkdown functions I tried:

inline equation: $A = \pi*r^{2}$ 

1. ordered list
2. item 2
 + sub-item 1
 + sub-item 2
 
Table Header  | Second Header
------------- | -------------
Table Cell    | Cell 2
Cell 3        | Cell 4 
